// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AlterTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['AlterTable'](arg1, arg2, arg3);
}

export function ApplyUpdate(arg1) {
  return window['go']['main']['App']['ApplyUpdate'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteRow(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteRow'](arg1, arg2, arg3, arg4);
}

export function DeleteRows(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteRows'](arg1, arg2, arg3, arg4);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DropTable(arg1, arg2) {
  return window['go']['main']['App']['DropTable'](arg1, arg2);
}

export function ExecuteQuery(arg1) {
  return window['go']['main']['App']['ExecuteQuery'](arg1);
}

export function ExecuteStatement(arg1) {
  return window['go']['main']['App']['ExecuteStatement'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetColumns(arg1, arg2) {
  return window['go']['main']['App']['GetColumns'](arg1, arg2);
}

export function GetDatabaseSchema(arg1) {
  return window['go']['main']['App']['GetDatabaseSchema'](arg1);
}

export function GetDatabases() {
  return window['go']['main']['App']['GetDatabases']();
}

export function GetTableData(arg1) {
  return window['go']['main']['App']['GetTableData'](arg1);
}

export function GetTableInfo(arg1, arg2) {
  return window['go']['main']['App']['GetTableInfo'](arg1, arg2);
}

export function GetTables(arg1) {
  return window['go']['main']['App']['GetTables'](arg1);
}

export function InsertRow(arg1, arg2, arg3) {
  return window['go']['main']['App']['InsertRow'](arg1, arg2, arg3);
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function IsFullscreen() {
  return window['go']['main']['App']['IsFullscreen']();
}

export function LoadConnections() {
  return window['go']['main']['App']['LoadConnections']();
}

export function RenameConnection(arg1, arg2) {
  return window['go']['main']['App']['RenameConnection'](arg1, arg2);
}

export function RestartApp() {
  return window['go']['main']['App']['RestartApp']();
}

export function SaveConnection(arg1, arg2) {
  return window['go']['main']['App']['SaveConnection'](arg1, arg2);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}

export function TruncateTable(arg1, arg2) {
  return window['go']['main']['App']['TruncateTable'](arg1, arg2);
}

export function UpdateConnection(arg1, arg2) {
  return window['go']['main']['App']['UpdateConnection'](arg1, arg2);
}

export function UpdateRow(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateRow'](arg1, arg2, arg3, arg4, arg5);
}

export function UseDatabase(arg1) {
  return window['go']['main']['App']['UseDatabase'](arg1);
}
