// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function AlterTable(arg1:string,arg2:string,arg3:database.TableAlteration):Promise<void>;

export function ApplyUpdate(arg1:string):Promise<void>;

export function CheckForUpdate():Promise<database.UpdateInfo>;

export function Connect(arg1:database.ConnectionConfig):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteRow(arg1:string,arg2:string,arg3:string,arg4:any):Promise<database.ExecuteResult>;

export function DeleteRows(arg1:string,arg2:string,arg3:string,arg4:Array<any>):Promise<database.ExecuteResult>;

export function Disconnect():Promise<void>;

export function DropTable(arg1:string,arg2:string):Promise<void>;

export function ExecuteQuery(arg1:string):Promise<database.QueryResult>;

export function ExecuteStatement(arg1:string):Promise<database.ExecuteResult>;

export function GetAppVersion():Promise<string>;

export function GetColumns(arg1:string,arg2:string):Promise<Array<database.ColumnInfo>>;

export function GetDatabaseSchema(arg1:string):Promise<Record<string, Array<string>>>;

export function GetDatabases():Promise<Array<database.DatabaseInfo>>;

export function GetTableData(arg1:database.TableDataRequest):Promise<database.TableDataResponse>;

export function GetTableInfo(arg1:string,arg2:string):Promise<database.TableDetails>;

export function GetTables(arg1:string):Promise<Array<database.TableInfo>>;

export function InsertRow(arg1:string,arg2:string,arg3:Record<string, any>):Promise<database.ExecuteResult>;

export function IsConnected():Promise<boolean>;

export function IsFullscreen():Promise<boolean>;

export function LoadConnections():Promise<Array<database.SavedConnection>>;

export function RenameConnection(arg1:string,arg2:string):Promise<void>;

export function RestartApp():Promise<void>;

export function SaveConnection(arg1:string,arg2:database.ConnectionConfig):Promise<void>;

export function TestConnection(arg1:database.ConnectionConfig):Promise<boolean>;

export function ToggleFullscreen():Promise<void>;

export function TruncateTable(arg1:string,arg2:string):Promise<void>;

export function UpdateConnection(arg1:string,arg2:database.ConnectionConfig):Promise<void>;

export function UpdateRow(arg1:string,arg2:string,arg3:string,arg4:any,arg5:Record<string, any>):Promise<database.ExecuteResult>;

export function UseDatabase(arg1:string):Promise<void>;
